### ISSUE TITLE
报错(Error)风格不统一

### ISSUE THREAD

**Issue by Cg1340** [oldjun/pi#1]
输入未定义标识符时，输出以“ERROR: ”开头的错误

![屏幕截图 2022-08-21 143628](https://user-images.githubusercontent.com/88421542/185778889-61c5d4f5-94b4-4b63-ae8e-f625e33b986e.jpg)

其他错误时，是输出以制表符(\t)开头的错误

![屏幕截图 2022-08-21 143645](https://user-images.githubusercontent.com/88421542/185779006-0fe93577-a5ee-48c5-b482-991898a1e32d.jpg)
![image](https://user-images.githubusercontent.com/88421542/185779047-b3ad9399-325c-484a-8167-ef1622d14f09.png)

**Comment by oldjun** [comment]
关于错误提示这块后续会完善，谢谢。目前主要花时间在制作官网，以及pi和底层go语言的互通。

**Comment by Cg1340** [comment]
好的
